# EXAMPLE application.yml with dummy values

SECRET_TOKEN:            "d4e5783de1c74c7a4e3a27578df6gdgf6g786g8df7g6g87d6fgb709"
FACEBOOK_APP_ID:         "35864341"
FACEBOOK_APP_SECRET:     "759a1e7sd7fvyfsd473"
TWITTER_CONSUMER_KEY:    "1UrRKJDF8SD7FSDF3S"
TWITTER_CONSUMER_SECRET: "5W7TE8KJJk787bnG0s"
TWITTER_OAUTH_TOKEN:     "716397744-3rHXFkFkjKjkjK78PQ5"
TWITTER_OAUTH_TOKEN_SECRET: "DuDJKFSD89SDFD"
LINKEDIN_API_KEY:        "2vjkJKjk4"
LINKEDIN_SECRET_KEY:     "5KLSJDFsE"
GMAIL_USERNAME:          "username@gmail.com"
GMAIL_PASSWORD:          "PASSWORD"
AWS_ACCESS_KEY_ID:       "ASDKLSDJFIA"
AWS_SECRET_ACCESS_KEY:   "7ASDFJksdfjskdlf87sdfKb"
AWS_S3_BUCKET:           "bucket"

development:
  MAILER_HOST: "localhost:3000"

test:
  MAILER_HOST: "localhost:3000"

production:
  MAILER_HOST: "domain.com"

